### ISSUE TITLE
Do you need any help on this?

### ISSUE THREAD

**Issue by ethanwillis** [smartcontractkit/solc-api#1]
There are no milestones. However I could see it being useful if this api would output reports to a tracker/CI system. Would that be helpful for you? Also what are some other things that would be good enhancements?

**Comment by se3000** [comment]
Hey, thanks for the offer. Can you be more clear about the tracker/CI integration, I'm not sure what would be integrated. For the most part, it is an intentionally minimal/lightweight app. I'd been thinking that custom integrations would be built separately, but I'm open to the idea.

On the note of CI, the repo doesn't have any tests. That would be worthwhile to add.

 Also, so far I've pretty much just matched the solc-js API, which has changed a little. It might be worth adding some sort of proxy API that we could support and keep consistent in the case that the solc-js API changes again in the future.

Do either of those sound like something you'd be interested in taking on?

**Comment by ethanwillis** [comment]
For tracker/CI integration I was actually thinking more about the code that would be sent to the /compile endpoint. If I had some solidity code that I was normally sending to this service that i have checked into version control..  I could have something like a gitlab runner that sends the solidity code to /compile and then reads back the build results. I'm thinking I would modify /compile to return more than just the basic compilation output and instead enhance it with some metadata about the build status. That would just be in case the regular compiler output doesn't already have all of the necessary information (I haven't written any solidity before, so I have no familiarity with the tooling).

As far as CI for this repo itself, yea I could write some tests and get some pass/fail badges in here. I also have another guy who would probably be interested in adding some test suites to this (and your other repos) if I don't have the time available. 

I could definitely break out the interface you're supporting with an adapter to the solc-js API, that shouldn't be too difficult. I'll take a crack at it sometime soon.

**Comment by ethanwillis** [comment]
I just started digging into the solc-js bindings and the solc standard input/output JSON. Looks like it already has all of the error messages we would possibly need in the output. 

https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description
