### ISSUE TITLE
Dogfooding

### ISSUE THREAD

**Issue by ethanwillis** [smartcontractkit/solc-api#2]
Funny dogfooding idea.. Could we not have solc.smartcontract.com be a chainlink node that provides compilation on demand services?

**Comment by se3000** [comment]
Yeah, definitely possible to make an oracle for providing on demand compilation.

I'd guess it is prohibitively expensive to pass full uncompiled solidity on chain, but there may be a gas efficient way to do it. With a couple of adapters in the middle you could pass around something like an IPFS address and have the oracle retrieve the content and compile it.

Cool idea, I'd be curious to see how it was used.
